---
- name: Install Nginx
  apt: pkg=nginx state=present update_cache=true cache_valid_time=3600
  register: nginxinstalled
  notify:
    #  This notifies any Handler named "Start Nginx" after the Task is run.
    - Start Nginx
  tags: packages
