
- name: Install NTP
  apt: package=ntp state=present update_cache=yes cache_valid_time=3600
  tags: packages

- name: Make sure NTP is started up
  service: name=ntp state=started enabled=yes
  tags: service

- name: set timezone to Europe/Rome
  timezone:
    name: Europe/Rome
  tags: configure
