---
# tasks file for denyhosts
- name: install denyhosts
  apt:
    name: denyhosts
    update_cache: yes
    cache_valid_time: 3600

- name: setting purge deny
  # this module preserve the remote file, but allow us a modification
  lineinfile: dest=/etc/denyhosts.conf regexp=^{{ item.key }}
              line="{{ item.key }} = {{ item.value }}"
  notify: restart denyhosts
  loop:
    - { key: 'PURGE_DENY', value: "{{ denyhosts_purge_deny }}"}
    - { key: 'DENY_THRESHOLD_ROOT', value: "{{ denyhosts_deny_threshold_root }}"}
    - { key: 'ADMIN_EMAIL', value: "{{ denyhosts_admin_email }}"}
    - { key: 'DENY_THRESHOLD_INVALID', value: "{{ denyhosts_deny_threshold_invalid }}"}
    - { key: 'DENY_THRESHOLD_VALID', value: "{{ denyhosts_deny_threshold_valid }}"}
    - { key: 'SYNC_UPLOAD', value: "{{ denyhosts_sync_upload }}"}
    - { key: 'SYNC_DOWNLOAD', value: "{{ denyhosts_sync_download }}"}
    - { key: 'SUSPICIOUS_LOGIN_REPORT_ALLOWED_HOSTS', value: "{{ denyhosts_suspicious }}"}

- name: uncomment options in purge deny
  lineinfile: dest=/etc/denyhosts.conf regexp="^#?{{ item.key }}"
              line="{{ item.key }} = {{ item.value }}"
  notify: restart denyhosts
  loop:
    - { key: 'RESET_ON_SUCCESS', value: "{{ denyhosts_reset_on_success }}"}
    - { key: 'SYNC_SERVER', value: "{{ denyhosts_sync_server }}"}

- name: disable iptable with denyhosts
  lineinfile: dest=/etc/denyhosts.conf regexp="^#?IPTABLES"
              line="#IPTABLES = /sbin/iptables"
  notify: restart denyhosts

- name: copy purge_denyhosts.sh script
  copy:
    src: purge_denyhosts.sh
    dest: /usr/local/bin/purge_denyhosts.sh
    mode: 0755

- name: copy denyhost allowed hosts
  copy:
    src: allowed-hosts
    dest: /var/lib/denyhosts/allowed-hosts

# state=restarted restart regardles of current state
- name: ensure denyhosts started
  service: name=denyhosts state=started enabled=yes
