---
- hosts: digitalocean
  remote_user: root

  roles:
    # install with: ansible-galaxy install andrewsomething.do-agent
    - andrewsomething.do-agent
    - apt
    - role: fail2ban
      tags: fail2ban
    - role: denyhosts
      tags: denyhosts
    - time
    - role: docker
      tags: docker
    - nginx
    - ufw
    - image
    - logwatch
    - user
    - injecttool
