---
- hosts: default
  become: true  # become superuser. Can be placed in task

  roles:
    - apt
    - time
    - role: docker
      tags: docker
    - nginx
    - image
    - user
    - injecttool
    - common_data_pool
