---
- hosts: default
  become: true  # become superuser. Can be placed in task

  roles:
    - apt
    - role: fail2ban
      tags: fail2ban
    - time
    - role: docker
      tags: docker
    - nginx
    - ufw
    - image
    - logwatch
    - user
    - injecttool
