---
- hosts: default
  become: true  # become superuser. Can be placed in task

  roles:
    - apt
    - time
    - docker
    - nginx
    - ufw
    - image
    - logwatch
    - denyhosts
    - user

vars_files:
  - vars/main.yml
