---
- hosts: production:testing
  remote_user: root

  roles:
    # install with: ansible-galaxy install andrewsomething.do-agent
    - role: andrewsomething.do-agent
      tags: do-agent
    - role: apt
      tags: packages
    - role: swapfile
      tags: swapfile
    - role: fail2ban
      tags: fail2ban
      fail2ban_ignoreip: 127.0.0.1/8 ::1 155.253.15.135 94.198.213.9
    - role: denyhosts
      tags: denyhosts
    - role: time
      tags: time
    - role: docker
      tags: docker
    - role: nginx
      tags: nginx
    - role: ufw
      tags: ufw
    - role: letsencrypt
      tags: ['letsencrypt', 'image']
    - role: image
      tags: image
    - role: logwatch
      tags: logwatch
    - role: user
      tags: user
    - role: injecttool
      tags: injecttool
    - role: common_data_pool
      tags: common_data_pool
    - role: geerlingguy.nodejs
      tags: nodejs
    - role: frontend
      tags: frontend
