---
- name: Create new user
  user:
    name: image
    password: "{{ image_password }}"
    shell: /bin/bash
    groups: docker, sudo
    append: yes
  tags: configure

- name: Create .ssh folder
  file:
    path: ~image/.ssh
    state: directory
    owner: image
    group: image
    mode: 0700
  tags: configure

- name: Upload SSH key
  copy:
    src: authorized_keys
    dest: ~image/.ssh/authorized_keys
    owner: image
    group: image
    mode: 0600
  tags: configure
