---
# install git lfs for injecttoool
- import_tasks: git-lfs.yml
  tags:
    - git-lfs

# tasks file for injecttool
- name: install InjectTool from git
  become: True
  become_user: image
  git:
    repo: https://github.com/cnr-ibba/IMAGE-InjectTool.git
    dest: ~image/IMAGE-InjectTool
    version: "{{ injecttool_git_version }}"

- name: Install git lfs hooks
  become: True
  become_user: image
  command: git lfs install
  args:
    chdir: ~image/IMAGE-InjectTool
    creates: ~image/IMAGE-InjectTool/.git/lfs

- name: Copy .env configuration
  become: True
  become_user: image
  template:
    src: env.j2
    dest: ~image/IMAGE-InjectTool/.env
