---
- name: Install "aptitude" package
  apt:
    name: aptitude
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: install mailutils
  apt:
    name: mailutils
    update_cache: yes
    cache_valid_time: 3600
