---
# tasks file for common_data_portal
- name: install CommonDataPool from git
  become: True
  become_user: image
  git:
    repo: https://github.com/cnr-ibba/IMAGE-CommonDataPool.git
    dest: ~image/IMAGE-CommonDataPool
    version: master

- name: Copy first .env configuration
  become: True
  become_user: image
  template:
    src: database.j2
    dest: ~image/IMAGE-CommonDataPool/image_backend/database1_env

- name: Copy second .env configuration
  become: True
  become_user: image
  template:
    src: django.j2
    dest: ~image/IMAGE-CommonDataPool/image_backend/api_service/.env
