---
# tasks file for common_data_portal
- name: install CommonDataPool from git
  become: True
  become_user: image
  git:
    repo: https://github.com/cnr-ibba/IMAGE-CommonDataPool.git
    dest: ~image/IMAGE-CommonDataPool
    version: master

- name: Copy Environment configuration
  become: True
  become_user: image
  template:
    src: environment.j2
    dest: ~image/IMAGE-CommonDataPool/.env
