# file: logwatch/tasks/main.yml

- name: Install logwatch and dependancies
  apt:
    name: ['logwatch']
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: packages

- name: Configure logwatch (/etc/logwatch/conf/logwatch.conf)
  template:
    src: logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: root
    mode: 0644
  tags: configure
