---
- name: Disable default configuration by removing link
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags: ['image-configure', 'configure']

- name: Remove the old configuration files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-enabled/image.conf
    - /etc/nginx/sites-available/image.conf
  tags: ['image-configure', 'configure']

- name: Remove default home page
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
  tags: ['image-data']

# ensure self signed certificates installed
# https://wiki.debian.org/Self-Signed_Certificate
- name: Installing self-signed certificates
  apt:
    name: ssl-cert
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags: ['packages', 'image-configure', 'configure']

- name: copy self-signed ssl params
  copy: src=ssl-params.conf dest=/etc/nginx/snippets/ssl-params.conf owner=root group=root
  notify: Reload Nginx
  tags: ['image-configure', 'configure']

- name: Download latest 4096 dbhparams
  get_url:
    url: https://2ton.com.au/dhparam/4096
    dest: /etc/nginx/dhparam.pem

- name: Copy nginx configuration for wp5image.eu domain
  template:
    src: wp5image.conf.j2
    dest: /etc/nginx/sites-available/wp5image.conf
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- stat:
    path: /etc/nginx/sites-available/wp5image.conf
  tags: ['image-configure', 'configure']
  register: wp5image

# create symlink if the src path exists
- name: Enable wp5image.eu stuff
  file:
    src: /etc/nginx/sites-available/wp5image.conf
    dest: /etc/nginx/sites-enabled/wp5image.conf
    state: link
  when: wp5image.stat.exists
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: Copy nginx configuration for image2020genebank.eu domain
  template:
    src: image2020genebank.conf.j2
    dest: /etc/nginx/sites-available/image2020genebank.conf
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- stat:
    path: /etc/nginx/sites-available/image2020genebank.conf
  tags: ['image-configure', 'configure']
  register: image2020genebank

# create symlink if the src path exists
- name: Enable wp5image.eu stuff
  file:
    src: /etc/nginx/sites-available/image2020genebank.conf
    dest: /etc/nginx/sites-enabled/image2020genebank.conf
    state: link
  when: image2020genebank.stat.exists
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: Copy maintenance page
  copy: src=maintenance.html dest=/usr/share/nginx/html owner=root group=root
  notify: Reload Nginx
  tags: ['image-data']

- name: Copy favicon.ico
  copy: src=favicon.ico dest=/usr/share/nginx/html owner=root group=root
  tags: ['image-data']

- name: Copy robots.txt
  copy: src=robots.txt dest=/usr/share/nginx/html owner=root group=root
  tags: ['image-data']

# https://stackoverflow.com/a/48560511/4385116
- name: Set image maintenance page
  file:
    src: /usr/share/nginx/html/maintenance.html
    dest: /usr/share/nginx/html/image_maintenance.html
    state: link
  tags: ['image-data']
