---
# tasks file for letsencrypt

# Installing Certbot
- apt_repository:
    repo: ppa:certbot/certbot
  tags: packages

- name: installing certbot
  apt:
    pkg:
      - python-certbot-nginx
      - python3-certbot-dns-digitalocean
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags: packages
