---
# tasks file for letsencrypt

# Installing Certbot
- apt_repository:
    repo: ppa:certbot/certbot
  tags: packages

- name: installing certbot
  apt:
    pkg:
      - python-certbot-nginx
      - python3-certbot-dns-digitalocean
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags: packages

# execute stuff for the old domain name
- import_tasks: old_domain.yml
  tags: ['image-configure', 'configure']

- name: listen for 433 ports on ipv4 for {{ domain_name }}
  replace:
    path: /etc/nginx/sites-available/image2020genebank.conf
    regexp: 'listen 80;'
    replace: 'listen 443 ssl;'
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: listen for 433 ports on ipv6 for {{ domain_name }}
  replace:
    path: /etc/nginx/sites-available/image2020genebank.conf
    regexp: 'listen \[\:\:\]\:80;'
    replace: 'listen [::]:443 ssl;'
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: replace protocol in redirects for {{ domain_name }}
  replace:
    path: /etc/nginx/sites-available/image2020genebank.conf
    regexp: 'return 307 http\:'
    replace: 'return 307 https:'
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: add SSL configuration for data portal for {{ domain_name }}
  blockinfile:
    path: /etc/nginx/sites-available/image2020genebank.conf
    marker: "  # {mark} data portal SSL"
    insertafter: "# SSL configuration for data portal"
    content: |2
        ssl_certificate /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ domain_name }}/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: add SSL configuration for InjectTool for {{ domain_name }}
  blockinfile:
    path: /etc/nginx/sites-available/image2020genebank.conf
    marker: "  # {mark} InjectTool SSL"
    insertafter: "# SSL configuration for InjectTool"
    content: |2
        ssl_certificate /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ domain_name }}/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: redirect http traffic to https for {{ domain_name }}
  blockinfile:
    path: /etc/nginx/sites-available/image2020genebank.conf
    block: |
      # redirect traffic to https port
      server {
        listen 80;
        listen [::]:80;
        server_name {{ image_server_name }};
        return 307 https://$host$request_uri;
      }

      server {
        listen 80;
        listen [::]:80;
        server_name {{ injecttool_server_name }};
        return 307 https://$host$request_uri;
      }
    marker: "# {mark} ANSIBLE REDIRECT"
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: redirect traffic from {{ domain_name }} to {{ image_server_name }}
  blockinfile:
    path: /etc/nginx/sites-available/image2020genebank.conf
    block: |
      # redirect traffic to https port
      server {
        listen 443;
        listen [::]:443;
        server_name {{ domain_name }};

        # define certificates, even for this redirect
        ssl_certificate /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ domain_name }}/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        return 307 https://{{ image_server_name }}$request_uri;
      }
    marker: "# {mark} ANSIBLE REDIRECT TO WWW"
  tags: ['image-configure', 'configure']
  notify: Reload Nginx
