---
# tasks file for letsencrypt

# Installing Certbot
- apt_repository:
    repo: ppa:certbot/certbot
  tags: packages

- name: installing certbot
  apt:
    pkg:
      - python-certbot-nginx
      - python3-certbot-dns-digitalocean
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags: packages

- name: enable NgINX reload after certificate renewal
  blockinfile:
    path: /etc/letsencrypt/cli.ini
    marker: "# {mark} ANSIBLE NgINX reload"
    block: |
      # https://blog.arnonerba.com/2019/01/lets-encrypt-how-to-automatically-restart-nginx-with-certbot
      deploy-hook = systemctl reload nginx
