---
# tasks file for letsencrypt

- name: listen for 433 ports on ipv4 for {{ old_domain_name }}
  replace:
    path: /etc/nginx/sites-available/wp5image.conf
    regexp: 'listen 80;'
    replace: 'listen 443 ssl;'
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: listen for 433 ports on ipv6 for {{ old_domain_name }}
  replace:
    path: /etc/nginx/sites-available/wp5image.conf
    regexp: 'listen \[\:\:\]\:80;'
    replace: 'listen [::]:443 ssl;'
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: replace protocol in redirects for {{ old_domain_name }}
  replace:
    path: /etc/nginx/sites-available/wp5image.conf
    regexp: 'return 307 http\:'
    replace: 'return 307 https:'
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: add SSL configuration for data portal for {{ old_domain_name }}
  blockinfile:
    path: /etc/nginx/sites-available/wp5image.conf
    marker: "  # {mark} data prortal SSL"
    insertafter: "# SSL configuration for data portal"
    content: |2
        ssl_certificate /etc/letsencrypt/live/{{ old_domain_name }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ old_domain_name }}/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: add SSL configuration for InjectTool for {{ old_domain_name }}
  blockinfile:
    path: /etc/nginx/sites-available/wp5image.conf
    marker: "  # {mark} InjectTool SSL"
    insertafter: "# SSL configuration for InjectTool"
    content: |2
        ssl_certificate /etc/letsencrypt/live/{{ old_domain_name }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ old_domain_name }}/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
  tags: ['image-configure', 'configure']
  notify: Reload Nginx


- name: redirect http traffic to https for {{ old_domain_name }}
  blockinfile:
    path: /etc/nginx/sites-available/wp5image.conf
    block: |
      server {
        listen 80;
        listen [::]:80;
        server_name {{ old_image_server_name }};
        return 307 https://{{ image_server_name }}$request_uri;
      }

      server {
        listen 80;
        listen [::]:80;
        server_name {{ old_injecttool_server_name }};
        return 307 https://{{ injecttool_server_name }}$request_uri;
      }
    marker: "# {mark} ANSIBLE REDIRECT"
  tags: ['image-configure', 'configure']
  notify: Reload Nginx

- name: redirect traffic from {{ old_domain_name }} to {{ image_server_name }}
  blockinfile:
    path: /etc/nginx/sites-available/wp5image.conf
    block: |
      # redirect traffic to https port
      server {
        listen 443;
        listen [::]:443;
        server_name {{ old_domain_name }};

        # define certificates, even for this redirect
        ssl_certificate /etc/letsencrypt/live/{{ old_domain_name }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ old_domain_name }}/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        return 307 https://{{ image_server_name }}$request_uri;
      }
    marker: "# {mark} ANSIBLE REDIRECT TO WWW"
  tags: ['image-configure', 'configure']
  notify: Reload Nginx
