---
- hosts: production # all

  roles:
    # to install: ansible-galaxy install cleberjsantos.ansible-ssmtp
    - cleberjsantos.ansible-ssmtp

  vars:
    ssmtp_hostname: "{{ ansible_hostname }}"
    ssmtp_auth_method: LOGIN
    ssmtp_server: smtp.gmail.com:587
    ssmtp_rewrite_domain: gmail.com
    # ssmtp_root, ssmtp_auth_user, ssmtp_auth_pass are defined in group_vars/production/vault
  tags:
    - mail
    - gmail
    - ssmtp
    - sendmail
